In [1]:
import sys
sys.path.append('..')
import torch
import numpy as np
import json
from pathlib import Path
from omegaconf import DictConfig
from datasets.video.dmlab_video_dataset import DmlabVideoDataset
from algorithms.rnn_diffusion_correction.models.vdt import *

/home/s224075134/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
batch_size = 1
num_frames = 3
input_size = 2
in_channels = 1
hidden_size=4
model_type = 'VDT-S/1'  # Use smaller model for testing

# Choose device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Create model
print(f"Creating {model_type} model...")
model = VDT(
    depth=1,
    num_heads=1,
    hidden_size=hidden_size,
    patch_size=1,
    input_size=input_size,
    in_channels=in_channels,
    num_frames=40,
    is_causal_crossattn=False
)
model = model.to(device)

_x = torch.randn(batch_size, num_frames, in_channels, input_size, input_size, device=device)
_z = torch.randn(batch_size, num_frames, hidden_size, device=device)
t = torch.randint(10,100, (batch_size,), device=device).long()  # Timestep tokens

Using device: cuda
Creating VDT-S/1 model...


In [5]:
x = _x.clone()
z = _z.clone()
x[:,1,...]=100
# z[:, 2,...]=210

model(x, z, t)

tensor([[[[[  3.7307,   3.3296],
           [  3.4312,   3.7017]]],


         [[[ 99.6866, 100.6962],
           [ 99.7997, 100.8094]]],


         [[[  2.4568,   0.1759],
           [  3.0913,   2.9595]]]]], device='cuda:0', grad_fn=<ViewBackward0>)

In [ ]:
tensor([[[[[3.7307, 3.3296],
           [3.4312, 3.7017]]],


         [[[1.4641, 1.5118],
           [3.3132, 1.4595]]],


         [[[2.4053, 0.1639],
           [3.0958, 3.0188]]]]], device='cuda:0', grad_fn=<ViewBackward0>)

SyntaxError: invalid syntax (853863817.py, line 11)

In [ ]:
tensor([[[[[ 0.1514,  1.5234],
           [ 0.9282,  1.1893]]],


         [[[-0.2945, -0.3422],
           [ 0.6772, -0.0202]]],


         [[[ 1.0792,  0.6043],
           [-0.2495,  0.7764]]]]], device='cuda:0', grad_fn=<ViewBackward0>)

SyntaxError: invalid syntax (1814243405.py, line 1)

In [ ]:
generate_mask_for_cross_attention(3, 2, 'cpu')

tensor([[ True, False, False],
        [ True, False, False],
        [ True,  True, False],
        [ True,  True, False],
        [ True,  True,  True],
        [ True,  True,  True]])